import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
 
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Website Builder",
    description: "Generated by create next app",
};

/**
 * @description Root layout component that wraps all pages with header and footer.
 * @param {Object} props - The component props.
 * @param {React.ReactNode} props.children - The child components to render.
 * @returns {JSX.Element} The rendered layout with header, main content, and footer.
 */
const RootLayout: React.FC<{
    children: React.ReactNode;
}> = ({ children }) => {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Header />
                <main className="min-h-screen">{children}</main>
                <Toaster richColors closeButton position="top-right" />
                <Footer />
            </body>
        </html>
    );
};

export default RootLayout;
